### PR TITLE
Save configuration JSON files indented

### PR DESCRIPTION
**Pull request by hobarrera**
Save configuration JSON files indented, so they're human readable and easier to hand-edit, diff, etc.

### CODE REVIEW

**Comment by hobarrera** [comment]
bump?

**Comment by hobarrera** [comment]
Thanks!

**Comment by spantaleev** [comment]
Thank you too!

Version 0.6.2 is now tagged and pushed to PyPI and AUR.

**Comment by hobarrera** [comment]
Awesome, thanks again! :D

**Pull request merged**
